# the Technology class.
class: "templates_skywater130.tech.TechInfoSkywater130"

# default EM spec calculation settings
em:
  # DC current temperature
  dc_temp: 70
  # RMS current allowable temperature increase
  rms_dt: 10

# transistor technology parameters
mos:
  # the transistor width minimum resolution.
  width_resolution: 1.0e-9
  # the transistor length minimum resolution.
  length_resolution: 1.0e-9

# routing grid parameters
routing_grid:
  1: [y, 52,  34]
  2: [x, 56,  70]
  3: [y, 66,  106]
  4: [x, 66,  60]
  5: [y, 284, 232]

# MOM cap parameters
mom_cap:
  standard:
    bot_dir: x
    info:
      # w, sp, margin, num_ports, port_tr_w
      1: !!python/tuple [64, 64, 120, 2, 1]
      2: !!python/tuple [64, 64, 120, 2, 1]
      3: !!python/tuple [64, 64, 120, 2, 1]
      4: !!python/tuple [64, 96, 96, 1, 1]
      5: !!python/tuple [116, 136, 136, 1, 1]
      6: !!python/tuple [116, 136, 136, 1, 1]
      7: !!python/tuple [138, 180, 180, 1, 1]
      8: !!python/tuple [440, 400, 400, 1, 1]

# fill parameters
fill:
  # sp_x, sp_y, margin_x, margin_y, density
  1: !!python/tuple [2000, 2000, 1000, 1000, 0.2]
  2: !!python/tuple [2000, 2000, 1000, 1000, 0.2]
  3: !!python/tuple [2000, 2000, 1000, 1000, 0.2]
  4: !!python/tuple [2000, 2000, 1000, 1000, 0.2]
  5: !!python/tuple [2000, 2000, 1000, 1000, 0.2]
  6: !!python/tuple [2000, 2000, 1000, 1000, 0.2]
  7: !!python/tuple [2000, 2000, 1000, 1000, 0.2]
  8: !!python/tuple [2000, 2000, 1000, 1000, 0.2]
